import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {  ClerkProvider} from '@clerk/nextjs'
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import { neobrutalism } from '@clerk/themes'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider
      appearance={{
         signIn: { baseTheme: neobrutalism },
      }}>
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem> 
      < Navbar />
        {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider> 
  );
}
